### PR TITLE
Update allowed origins to accomodate new demo URL

### PR DESCRIPTION
**Pull request by aguestuser**
- Demo app has new url (`https://demo.whereat.io`)
- To avoid CORS conflicts, edit allowed origin to this URL,
  not old one (`https://whereat.io`)

### CODE REVIEW

**Comment by aguestuser** [comment]
Note: this is a super-small and time-sensitive PR (need it for the demo linked to from the splash page to work!) , so I'm going to take the liberty of merging it myself. Hope that's cool! <3

**Comment by aguestuser** [comment]
Note: this is a super-small and time-sensitive PR (need it for the demo linked to from the splash page to work!) , so I took the liberty of merging it myself. Hope that's cool! <3

**Comment by madelynfreed** [comment]
Yes cool!

On Thu, Dec 3, 2015 at 7:38 PM, Austin Guest notifications@github.com
wrote:

> Note: this is a super-small and time-sensitive PR (need it for the demo
> linked to from the splash page to work!) , so I'm going to take the liberty
> of merging it myself. Hope that's cool! <3
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/whereat/whereat-server/pull/5#issuecomment-161837812.

## 

914.924.3879
New York

**Comment by aguestuser** [comment]
huzzah! :)

On Thu, Dec 3, 2015 at 7:39 PM, madelynfreed notifications@github.com
wrote:

> Yes cool!
> 
> On Thu, Dec 3, 2015 at 7:38 PM, Austin Guest notifications@github.com
> wrote:
> 
> > Note: this is a super-small and time-sensitive PR (need it for the demo
> > linked to from the splash page to work!) , so I'm going to take the
> > liberty
> > of merging it myself. Hope that's cool! <3
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/whereat/whereat-server/pull/5#issuecomment-161837812
> > .
> 
> ## 
> 
> 914.924.3879
> New York
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/whereat/whereat-server/pull/5#issuecomment-161837958.

## 

Austin Guest
guest.austin@gmail.com
@aguestuser http://twitter.com/aguestuser
831-917-6400

**Pull request merged**
